version: '3.7'

networks:
    laravel:
        driver: bridge

services:
  laravel:
    build:
      context: ./backend-app
      dockerfile: DockerFile
    container_name: laravel_app
    ports:
      - "9000:9000"
    volumes:
      - ./backend-app:/var/www/app
    depends_on:
      - mysql
      - redis
    networks:
      - laravel

  react:
    build:
      context: ./fe-knowledge
      dockerfile: DockerFile
    container_name: react_app
    ports:
      - "3000:3000"
    volumes:
      - ./fe-knowledge:/var/www
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - laravel

  nginx:
     image: nginx
     ports:
      - 8000:8000
     volumes:
      - ./backend-app:/var/www/app
      - ./backend-app/nginx/default.conf:/etc/nginx/conf.d/default.conf
     depends_on:
      - laravel
     networks:
      - laravel

  mysql:
    image: mysql:5.7
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: nhoncq
      MYSQL_USER: nhoncq
      MYSQL_PASSWORD: nhoncq
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"
    networks:
      - laravel

volumes:
  mysql_data:
